version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: countrycodesdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: strngpswrd
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: openjdk:17-jdk
    container_name: spring_boot_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]

volumes:
  mysql_data:
